name: npm-publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      # Publish to npm
      - run:
          git clone https://zixiCat:${{ secrets.REPO_EASY_CREATE_REACT_CONTEXT_TOKEN }}@github.com/zixiCat/scripts.git ./zixicat;
          node ./zixicat/rollup-publish;
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
